language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update

install:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    email: false
