language: php

php:
  - '7.0'
  - '7.1'
  - nightly

branches:
  only:
    - master

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - php: '7.0'
      env:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COVERAGE="true"
        - PHPUNIT_FLAGS="--coverage-text --coverage-clover=coverage.xml"
        - SYMFONY_VERSION="~3.0.0"
    - php: '7.0'
      env: SYMFONY_VERSION='~3.1.0'
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.bin/

before_install:
  - set -eo pipefail
  - OCULAR_BIN=$HOME/.bin/ocular.phar
  - PHPUNIT_BIN='vendor/bin/phpunit'
  - PHPUNIT_CONFIG='phpunit.xml.dist'
  - PHPUNIT_FLAGS='--stop-on-failure --verbose'
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - |
    if [ -z "$COVERAGE" ] && [ -f "$XDEBUG_INI" ]; then
      phpenv config-rm xdebug.ini
    fi
  - |
    if [ "$SYMFONY_VERSION" != "" ]; then
      composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update
    fi
  - |
    if [ -n "$COVERAGE" ] && [ ! -e $OCULAR_BIN ]; then
      wget https://scrutinizer-ci.com/ocular.phar -O $OCULAR_BIN
      alias ocular="php $OCULAR_BIN"
    fi
  - mysql -u root -e 'create database hautelook_alice_bundle;'

install:
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - |
    if [ -n "$COVERAGE" ]; then
        phpdbg -qrr $PHPUNIT_BIN -c $PHPUNIT_CONFIG $PHPUNIT_FLAGS --testdox --coverage-text
    else
        $PHPUNIT_BIN -c $PHPUNIT_CONFIG $PHPUNIT_FLAGS
    fi

after_script:
  - |
    if [ -n "$COVERAGE" ]; then
      ocular code-coverage:upload --format=php-clover coverage.xml
    fi

notifications:
  email: false
